version: "3.9"
services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=web-example
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector-gateway:4317
      - INSECURE_MODE=true
    depends_on:
        collector-gateway:
          condition: service_started
  #  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.52.0
    ports:
      - "16686:16686"
  # Collector
  collector-gateway:
    image: otel/opentelemetry-collector:0.90.1
    volumes:
      - ./config/collector-gateway.yaml:/etc/collector-gateway.yaml
    command: [ "--config=/etc/collector-gateway.yaml" ]
    ports:
      - "4317:4317"        # OTLP gRPC receiver
      - "4318:4318"        # OTLP HTTP receiver
    depends_on:
      - jaeger-all-in-one
