# collect traces in otlp format and export them to jaeger
receivers:
    otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

processors:
    batch:

exporters:
  logging:
    verbosity: Normal
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

service:
  pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp, logging]
